//! Generated by `rustible init` (rustible 0.0.1). Do not edit.
//!
//! Discovers every file under `playbooks/` that carries `#[rustible::playbook]`
//! and writes the registry `src/main.rs` includes. Playbooks go in
//! `playbooks/`, shared code in `src/lib.rs`. Regenerate this file with
//! `rustible init --refresh`.

fn main() {
    rustible_build::discover();
}
