//! Embed the vendored musl headers (`vendor/musl-headers/`) into the binary.
//!
//! `rustible` unpacks them into a workspace's cache directory and points the C
//! compiler at them when it cross-builds a playbook for
//! `x86_64-unknown-linux-musl`, because the TLS provider (`ring`) compiles C
//! that needs real libc headers on that target. Embedding rather than reading
//! them from the repository is what makes `cargo install rustible-cli` enough:
//! an installed binary has no checkout to read from.
//!
//! This writes `$OUT_DIR/musl_headers.rs`, one `include_bytes!` per header, and
//! `src/toolchain.rs` includes it.

use std::path::{Path, PathBuf};

fn main() {
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let dir = root.join("vendor/musl-headers/x86_64/include");
    println!("cargo:rerun-if-changed=vendor/musl-headers");

    let mut files = Vec::new();
    walk(&dir, &mut files);
    files.sort();
    assert!(
        !files.is_empty(),
        "no headers under {}; the vendored musl tree is missing",
        dir.display()
    );

    let mut code = String::from(
        "/// Every vendored musl header for `x86_64-unknown-linux-musl`, as\n\
         /// (path below `include/`, bytes). Generated by `build.rs`.\n\
         pub(crate) static X86_64_MUSL_HEADERS: &[(&str, &[u8])] = &[\n",
    );
    for path in &files {
        let rel = path
            .strip_prefix(&dir)
            .expect("walked under dir")
            .to_str()
            .expect("header paths are utf-8")
            .replace('\\', "/");
        code.push_str(&format!(
            "    ({rel:?}, include_bytes!({:?})),\n",
            path.display()
        ));
    }
    code.push_str("];\n");
    std::fs::write(out.join("musl_headers.rs"), code).expect("writing musl_headers.rs");
}

fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries =
        std::fs::read_dir(dir).unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()));
    for entry in entries {
        let path = entry.expect("directory entry").path();
        if path.is_dir() {
            walk(&path, out);
        } else {
            out.push(path);
        }
    }
}
